apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
      containers:
      - args:
        - --datadir=/var/data
        image: tkeber/bitcoind-docker:latest
        name: bitcoin
        volumeMounts:
        - mountPath: /var/data
          name: data
      - env:
          - name: BITCOIN_RPC_HOST
            value: bitcoin
          - name: BITCOIN_RPC_USER
            value: alice
          - name: BITCOIN_RPC_PASSWORD
            value: DONT_USE_THIS_YOU_WILL_GET_ROBBED_8ak1gI25KFTvjovL3gAM967mies3E=
        image: jvstein/bitcoin-prometheus-exporter:v0.7.0
        name: bitcoin-prometheus-exporter
        ports:
          - containerPort: 9332
            name: metrics
      tolerations: []
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: bitcoin